# Generated by Django 4.0.1 on 2022-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
    ]
